name: mfm
description: A MFM (Misskey Flavored Markup language) Renderer for Flutter.
version: 1.0.0
homepage: https://github.com/shiosyakeyakini-info/mfm_renderer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  colorfilter_generator: ^0.0.8
  flutter:
    sdk: flutter
  mfm_parser: ^1.0.3
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
